// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: entities/process_instance.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DefinitionId  string                 `protobuf:"bytes,3,opt,name=definition_id,json=definitionId,proto3" json:"definition_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Variables     *structpb.Struct       `protobuf:"bytes,5,opt,name=variables,proto3" json:"variables,omitempty"`
	ActiveNodes   []string               `protobuf:"bytes,6,rep,name=active_nodes,json=activeNodes,proto3" json:"active_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInstance) Reset() {
	*x = ProcessInstance{}
	mi := &file_entities_process_instance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInstance) ProtoMessage() {}

func (x *ProcessInstance) ProtoReflect() protoreflect.Message {
	mi := &file_entities_process_instance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInstance.ProtoReflect.Descriptor instead.
func (*ProcessInstance) Descriptor() ([]byte, []int) {
	return file_entities_process_instance_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessInstance) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProcessInstance) GetDefinitionId() string {
	if x != nil {
		return x.DefinitionId
	}
	return ""
}

func (x *ProcessInstance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessInstance) GetVariables() *structpb.Struct {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *ProcessInstance) GetActiveNodes() []string {
	if x != nil {
		return x.ActiveNodes
	}
	return nil
}

var File_entities_process_instance_proto protoreflect.FileDescriptor

const file_entities_process_instance_proto_rawDesc = "" +
	"\n" +
	"\x1fentities/process_instance.proto\x12\aprocess\x1a\x1cgoogle/protobuf/struct.proto\"\xd7\x01\n" +
	"\x0fProcessInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12#\n" +
	"\rdefinition_id\x18\x03 \x01(\tR\fdefinitionId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x125\n" +
	"\tvariables\x18\x05 \x01(\v2\x17.google.protobuf.StructR\tvariables\x12!\n" +
	"\factive_nodes\x18\x06 \x03(\tR\vactiveNodesB\x96\x01\n" +
	"\vcom.processB\x14ProcessInstanceProtoP\x01Z5github.com/gsoultan/gobpm/api/proto/entities;entities\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_entities_process_instance_proto_rawDescOnce sync.Once
	file_entities_process_instance_proto_rawDescData []byte
)

func file_entities_process_instance_proto_rawDescGZIP() []byte {
	file_entities_process_instance_proto_rawDescOnce.Do(func() {
		file_entities_process_instance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_process_instance_proto_rawDesc), len(file_entities_process_instance_proto_rawDesc)))
	})
	return file_entities_process_instance_proto_rawDescData
}

var file_entities_process_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entities_process_instance_proto_goTypes = []any{
	(*ProcessInstance)(nil), // 0: process.ProcessInstance
	(*structpb.Struct)(nil), // 1: google.protobuf.Struct
}
var file_entities_process_instance_proto_depIdxs = []int32{
	1, // 0: process.ProcessInstance.variables:type_name -> google.protobuf.Struct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_entities_process_instance_proto_init() }
func file_entities_process_instance_proto_init() {
	if File_entities_process_instance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_process_instance_proto_rawDesc), len(file_entities_process_instance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_process_instance_proto_goTypes,
		DependencyIndexes: file_entities_process_instance_proto_depIdxs,
		MessageInfos:      file_entities_process_instance_proto_msgTypes,
	}.Build()
	File_entities_process_instance_proto = out.File
	file_entities_process_instance_proto_goTypes = nil
	file_entities_process_instance_proto_depIdxs = nil
}
