// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: entities/task.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId       string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	InstanceId      string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Node            *Node                  `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	Name            string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Assignee        string                 `protobuf:"bytes,7,opt,name=assignee,proto3" json:"assignee,omitempty"`
	CandidateUsers  []*User                `protobuf:"bytes,8,rep,name=candidate_users,json=candidateUsers,proto3" json:"candidate_users,omitempty"`
	CandidateGroups []*Group               `protobuf:"bytes,9,rep,name=candidate_groups,json=candidateGroups,proto3" json:"candidate_groups,omitempty"`
	Priority        int32                  `protobuf:"varint,10,opt,name=priority,proto3" json:"priority,omitempty"`
	DueDate         string                 `protobuf:"bytes,11,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Variables       *structpb.Struct       `protobuf:"bytes,13,opt,name=variables,proto3" json:"variables,omitempty"`
	FormKey         string                 `protobuf:"bytes,14,opt,name=form_key,json=formKey,proto3" json:"form_key,omitempty"`
	FormDefinition  string                 `protobuf:"bytes,15,opt,name=form_definition,json=formDefinition,proto3" json:"form_definition,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_entities_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_entities_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_entities_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Task) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Task) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetAssignee() string {
	if x != nil {
		return x.Assignee
	}
	return ""
}

func (x *Task) GetCandidateUsers() []*User {
	if x != nil {
		return x.CandidateUsers
	}
	return nil
}

func (x *Task) GetCandidateGroups() []*Group {
	if x != nil {
		return x.CandidateGroups
	}
	return nil
}

func (x *Task) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Task) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *Task) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Task) GetVariables() *structpb.Struct {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *Task) GetFormKey() string {
	if x != nil {
		return x.FormKey
	}
	return ""
}

func (x *Task) GetFormDefinition() string {
	if x != nil {
		return x.FormDefinition
	}
	return ""
}

var File_entities_task_proto protoreflect.FileDescriptor

const file_entities_task_proto_rawDesc = "" +
	"\n" +
	"\x13entities/task.proto\x12\aprocess\x1a\x1cgoogle/protobuf/struct.proto\x1a\x13entities/node.proto\x1a\x13entities/user.proto\x1a\x14entities/group.proto\"\x85\x04\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12!\n" +
	"\x04node\x18\x04 \x01(\v2\r.process.NodeR\x04node\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1a\n" +
	"\bassignee\x18\a \x01(\tR\bassignee\x126\n" +
	"\x0fcandidate_users\x18\b \x03(\v2\r.process.UserR\x0ecandidateUsers\x129\n" +
	"\x10candidate_groups\x18\t \x03(\v2\x0e.process.GroupR\x0fcandidateGroups\x12\x1a\n" +
	"\bpriority\x18\n" +
	" \x01(\x05R\bpriority\x12\x19\n" +
	"\bdue_date\x18\v \x01(\tR\adueDate\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x125\n" +
	"\tvariables\x18\r \x01(\v2\x17.google.protobuf.StructR\tvariables\x12\x19\n" +
	"\bform_key\x18\x0e \x01(\tR\aformKey\x12'\n" +
	"\x0fform_definition\x18\x0f \x01(\tR\x0eformDefinitionB\x8b\x01\n" +
	"\vcom.processB\tTaskProtoP\x01Z5github.com/gsoultan/gobpm/api/proto/entities;entities\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_entities_task_proto_rawDescOnce sync.Once
	file_entities_task_proto_rawDescData []byte
)

func file_entities_task_proto_rawDescGZIP() []byte {
	file_entities_task_proto_rawDescOnce.Do(func() {
		file_entities_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_task_proto_rawDesc), len(file_entities_task_proto_rawDesc)))
	})
	return file_entities_task_proto_rawDescData
}

var file_entities_task_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entities_task_proto_goTypes = []any{
	(*Task)(nil),            // 0: process.Task
	(*Node)(nil),            // 1: process.Node
	(*User)(nil),            // 2: process.User
	(*Group)(nil),           // 3: process.Group
	(*structpb.Struct)(nil), // 4: google.protobuf.Struct
}
var file_entities_task_proto_depIdxs = []int32{
	1, // 0: process.Task.node:type_name -> process.Node
	2, // 1: process.Task.candidate_users:type_name -> process.User
	3, // 2: process.Task.candidate_groups:type_name -> process.Group
	4, // 3: process.Task.variables:type_name -> google.protobuf.Struct
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_entities_task_proto_init() }
func file_entities_task_proto_init() {
	if File_entities_task_proto != nil {
		return
	}
	file_entities_node_proto_init()
	file_entities_user_proto_init()
	file_entities_group_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_task_proto_rawDesc), len(file_entities_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_task_proto_goTypes,
		DependencyIndexes: file_entities_task_proto_depIdxs,
		MessageInfos:      file_entities_task_proto_msgTypes,
	}.Build()
	File_entities_task_proto = out.File
	file_entities_task_proto_goTypes = nil
	file_entities_task_proto_depIdxs = nil
}
