// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: endpoints/list_tasks_by_candidates.proto

package endpoints

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTasksByCandidatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Groups        []string               `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksByCandidatesRequest) Reset() {
	*x = ListTasksByCandidatesRequest{}
	mi := &file_endpoints_list_tasks_by_candidates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksByCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksByCandidatesRequest) ProtoMessage() {}

func (x *ListTasksByCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_list_tasks_by_candidates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksByCandidatesRequest.ProtoReflect.Descriptor instead.
func (*ListTasksByCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_endpoints_list_tasks_by_candidates_proto_rawDescGZIP(), []int{0}
}

func (x *ListTasksByCandidatesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListTasksByCandidatesRequest) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

var File_endpoints_list_tasks_by_candidates_proto protoreflect.FileDescriptor

const file_endpoints_list_tasks_by_candidates_proto_rawDesc = "" +
	"\n" +
	"(endpoints/list_tasks_by_candidates.proto\x12\aprocess\x1a\x1aendpoints/list_tasks.proto\"O\n" +
	"\x1cListTasksByCandidatesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06groups\x18\x02 \x03(\tR\x06groupsB\x9e\x01\n" +
	"\vcom.processB\x1aListTasksByCandidatesProtoP\x01Z7github.com/gsoultan/gobpm/api/proto/endpoints;endpoints\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_endpoints_list_tasks_by_candidates_proto_rawDescOnce sync.Once
	file_endpoints_list_tasks_by_candidates_proto_rawDescData []byte
)

func file_endpoints_list_tasks_by_candidates_proto_rawDescGZIP() []byte {
	file_endpoints_list_tasks_by_candidates_proto_rawDescOnce.Do(func() {
		file_endpoints_list_tasks_by_candidates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoints_list_tasks_by_candidates_proto_rawDesc), len(file_endpoints_list_tasks_by_candidates_proto_rawDesc)))
	})
	return file_endpoints_list_tasks_by_candidates_proto_rawDescData
}

var file_endpoints_list_tasks_by_candidates_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_endpoints_list_tasks_by_candidates_proto_goTypes = []any{
	(*ListTasksByCandidatesRequest)(nil), // 0: process.ListTasksByCandidatesRequest
}
var file_endpoints_list_tasks_by_candidates_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_endpoints_list_tasks_by_candidates_proto_init() }
func file_endpoints_list_tasks_by_candidates_proto_init() {
	if File_endpoints_list_tasks_by_candidates_proto != nil {
		return
	}
	file_endpoints_list_tasks_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoints_list_tasks_by_candidates_proto_rawDesc), len(file_endpoints_list_tasks_by_candidates_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpoints_list_tasks_by_candidates_proto_goTypes,
		DependencyIndexes: file_endpoints_list_tasks_by_candidates_proto_depIdxs,
		MessageInfos:      file_endpoints_list_tasks_by_candidates_proto_msgTypes,
	}.Build()
	File_endpoints_list_tasks_by_candidates_proto = out.File
	file_endpoints_list_tasks_by_candidates_proto_goTypes = nil
	file_endpoints_list_tasks_by_candidates_proto_depIdxs = nil
}
