// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: endpoints/list_definitions.proto

package endpoints

import (
	entities "github.com/gsoultan/gobpm/api/proto/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListDefinitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDefinitionsRequest) Reset() {
	*x = ListDefinitionsRequest{}
	mi := &file_endpoints_list_definitions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDefinitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDefinitionsRequest) ProtoMessage() {}

func (x *ListDefinitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_list_definitions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDefinitionsRequest.ProtoReflect.Descriptor instead.
func (*ListDefinitionsRequest) Descriptor() ([]byte, []int) {
	return file_endpoints_list_definitions_proto_rawDescGZIP(), []int{0}
}

func (x *ListDefinitionsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListDefinitionsResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Definitions   []*entities.ProcessDefinition `protobuf:"bytes,1,rep,name=definitions,proto3" json:"definitions,omitempty"`
	Error         string                        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDefinitionsResponse) Reset() {
	*x = ListDefinitionsResponse{}
	mi := &file_endpoints_list_definitions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDefinitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDefinitionsResponse) ProtoMessage() {}

func (x *ListDefinitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_list_definitions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDefinitionsResponse.ProtoReflect.Descriptor instead.
func (*ListDefinitionsResponse) Descriptor() ([]byte, []int) {
	return file_endpoints_list_definitions_proto_rawDescGZIP(), []int{1}
}

func (x *ListDefinitionsResponse) GetDefinitions() []*entities.ProcessDefinition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

func (x *ListDefinitionsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_endpoints_list_definitions_proto protoreflect.FileDescriptor

const file_endpoints_list_definitions_proto_rawDesc = "" +
	"\n" +
	" endpoints/list_definitions.proto\x12\aprocess\x1a\x19entities/definition.proto\"7\n" +
	"\x16ListDefinitionsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"m\n" +
	"\x17ListDefinitionsResponse\x12<\n" +
	"\vdefinitions\x18\x01 \x03(\v2\x1a.process.ProcessDefinitionR\vdefinitions\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB\x98\x01\n" +
	"\vcom.processB\x14ListDefinitionsProtoP\x01Z7github.com/gsoultan/gobpm/api/proto/endpoints;endpoints\xa2\x02\x03PXX\xaa\x02\aProcess\xca\x02\aProcess\xe2\x02\x13Process\\GPBMetadata\xea\x02\aProcessb\x06proto3"

var (
	file_endpoints_list_definitions_proto_rawDescOnce sync.Once
	file_endpoints_list_definitions_proto_rawDescData []byte
)

func file_endpoints_list_definitions_proto_rawDescGZIP() []byte {
	file_endpoints_list_definitions_proto_rawDescOnce.Do(func() {
		file_endpoints_list_definitions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoints_list_definitions_proto_rawDesc), len(file_endpoints_list_definitions_proto_rawDesc)))
	})
	return file_endpoints_list_definitions_proto_rawDescData
}

var file_endpoints_list_definitions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_endpoints_list_definitions_proto_goTypes = []any{
	(*ListDefinitionsRequest)(nil),     // 0: process.ListDefinitionsRequest
	(*ListDefinitionsResponse)(nil),    // 1: process.ListDefinitionsResponse
	(*entities.ProcessDefinition)(nil), // 2: process.ProcessDefinition
}
var file_endpoints_list_definitions_proto_depIdxs = []int32{
	2, // 0: process.ListDefinitionsResponse.definitions:type_name -> process.ProcessDefinition
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_endpoints_list_definitions_proto_init() }
func file_endpoints_list_definitions_proto_init() {
	if File_endpoints_list_definitions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoints_list_definitions_proto_rawDesc), len(file_endpoints_list_definitions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpoints_list_definitions_proto_goTypes,
		DependencyIndexes: file_endpoints_list_definitions_proto_depIdxs,
		MessageInfos:      file_endpoints_list_definitions_proto_msgTypes,
	}.Build()
	File_endpoints_list_definitions_proto = out.File
	file_endpoints_list_definitions_proto_goTypes = nil
	file_endpoints_list_definitions_proto_depIdxs = nil
}
